# Generated by Django 5.2.7 on 2025-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antennas',
            fields=[
                ('antenna_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_number', models.IntegerField()),
                ('orientation', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'antennas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('detection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('epc', models.CharField(max_length=120)),
                ('rssi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('phase_angle', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('frequency_mhz', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('detected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'detections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGroups',
            fields=[
                ('pk', models.CompositePrimaryKey('item_id', 'group_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemProjects',
            fields=[
                ('pk', models.CompositePrimaryKey('item_id', 'project_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('tag_id', models.CharField(max_length=120, unique=True)),
                ('epc', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('tag_type', models.CharField(blank=True, max_length=60, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=8)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('pk', models.CompositePrimaryKey('project_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'readers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageLocations',
            fields=[
                ('storage_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'storage_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
