# Generated by Django 5.2.7 on 2025-11-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgroups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemprojects',
            options={'verbose_name': 'Item Project', 'verbose_name_plural': 'Item Projects'},
        ),
    ]
