# Generated by Django 5.2.7 on 2025-11-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_itemgroups_options_alter_itemprojects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgroups',
            options={'managed': False, 'verbose_name': 'Item Group', 'verbose_name_plural': 'Item Groups'},
        ),
        migrations.AlterModelOptions(
            name='itemprojects',
            options={'managed': False, 'verbose_name': 'Item Project', 'verbose_name_plural': 'Item Projects'},
        ),
    ]
